package com.xspaceagi.system.spec.exception;

import lombok.Getter;

/**
 * 异常枚举
 */
@Getter
public enum BizExceptionCodeEnum implements IBizExceptionCodeEnum {


    /**
     * 系统异常
     */
    systemUnexpectedError("1000", "系统异常，请稍后再试", "A system error occurred. Please try again later.", "系统未预料统一捕获的异常，例如空指针、数组越界等"),
    systemMissingRequiredParameter("1010", "系统异常，请稍后再试", "A system error occurred. Please try again later.", "参数异常，必填参数未传递"),
    systemInternalRpcFailure("1020", "系统异常，请稍后再试", "A system error occurred. Please try again later.", "依赖服务（内部系统RPC）调用异常，超时、服务不可用等"),
    systemExternalHttpFailure("1030", "系统异常，请稍后再试", "A system error occurred. Please try again later.", "三方服务（外部系统HTTP）调用异常，超时、对方系统异常等"),
    systemDataLayerFailure("1040", "系统异常，请稍后再试", "A system error occurred. Please try again later.", "数据层（MYSQL、ES等）异常，主键冲突、超时等"),
    systemCacheFailure("1050", "系统异常，请稍后再试", "A system error occurred. Please try again later.", "缓存异常"),


    //参数缺失：统一用「参数'xx'不能为空」，具体名称由调用方传入（与 i18n key fieldRequiredButEmpty 对应）
    validationFailedWithDetail("2006", "%s", "%s", "参数校验失败"),
    fieldRequiredButEmpty("2007", "参数'%s'不能为空", "Parameter '%s' is required.", "通用：必填项"),
    /** 通用：数据/记录不存在（知识库、Compose、自定义页等共用） */
    resourceDataNotFound("5001", "数据不存在", "Data does not exist.", "通用"),
    /** 通用：配置记录不存在（IM、沙箱、生态市场、Agent 组件等共用） */
    configNotFound("8001", "配置不存在", "Configuration does not exist.", "通用"),
    /** 通用：需要登录态 */
    userNotLoggedIn("3177", "用户未登录", "User is not signed in.", "认证"),
    /** 通用：物理表不存在（Compose DDL、助手查询等共用） */
    tableNotFound("6013", "表不存在", "Table does not exist.", "通用"),
    /** 通用：无权限（合并原 systemOperationDenied / systemOperationPermissionDenied / systemPermissionDeniedShort） */
    permissionDenied("3020", "无权限", "Permission denied.", "通用"),

    //系统管理
    systemUserNotFound("3001", "用户不存在", "User does not exist.", "用户不存在"),
    systemUserStatusInvalid("3002", "用户启用状态标记异常", "Invalid user enabled status flag.", "用户启用状态标记异常"),
    systemLoginCredentialsInvalid("3003", "用户或密码错误", "Invalid username or password.", "用户或密码错误"),
    systemUserOrPhoneAlreadyExists("3004", "用户或手机号已存在", "Username or phone number already exists.", "用户或手机号已存在"),
    systemOrgNotFound("3005", "机构不存在", "Organization does not exist.", "机构不存在"),
    systemBackupFileNotFound("3006", "备份文件不存在,文件=%s", "Backup file not found, file=%s", "备份文件不存在"),
    systemBackupRecordNotFound("3007", "备份记录不存在", "Backup record does not exist.", "备份记录不存在"),
    systemBackupFileAlreadyExists("3008", "备份文件已存在,为避免覆盖文件,请重试备份操作", "Backup file already exists. Retry the backup to avoid overwriting.", "备份文件已存在,为避免覆盖文件,请重试备份操作"),
    systemBackupDownloadIoError("3009", "下载备份文件时发生IO异常,%s", "I/O error while downloading backup file: %s", ""),
    systemPasswordIncorrect("3010", "密码错误", "Incorrect password.", ""),
    systemNewPasswordSameAsOld("3011", "新密码不能和旧密码相同", "New password must differ from the old password.", ""),
    systemMenuNotFound("3012", "菜单不存在,KEY=%s", "Menu not found, KEY=%s", ""),
    systemRegistrationClosed("3013", "注册已关闭", "Registration is disabled.", "认证"),
    systemAccountDisabled("3014", "账号已被禁用", "Account has been disabled.", "认证"),
    systemLoginIdentifierOrPasswordWrong("3015", "用户不存在或密码错误", "User does not exist or password is incorrect.", "认证"),
    systemUserNotLoggedInWeb("3016", "用户未登陆", "User is not signed in.", "认证"),
    systemMenuCodeAlreadyExists("3018", "已存在此菜单编码", "This menu code already exists.", "菜单"),
    systemPersonalSpaceDeleteForbidden("3021", "个人空间不允许删除", "Personal space cannot be deleted.", "空间"),
    systemParamRequired("3022", "参数不能为空", "Parameter cannot be empty.", "参数"),
    systemCannotAddOwner("3023", "不能添加Owner", "Cannot add Owner.", "空间成员"),
    systemCannotUpdateToOwner("3024", "不能更新为Owner", "Cannot change role to Owner.", "空间成员"),
    systemCannotDeleteSelf("3025", "不能删除自己", "You cannot delete yourself.", "空间成员"),
    systemSpaceNotFound("3026", "空间不存在", "Space does not exist.", "空间"),
    systemCannotDeleteSpaceCreator("3027", "不能删除创建者", "Cannot remove the space creator.", "空间成员"),
    systemEmailFormatInvalid("3028", "邮箱格式不正确", "Invalid email format.", "用户"),
    systemEmailAlreadyInUse("3029", "邮箱已被占用", "Email is already in use.", "用户"),
    systemPhoneAlreadyInUse("3030", "手机号已被占用", "Phone number is already in use.", "用户"),
    systemSmsNotConfiguredDevHint("3031", "系统未配置短信服务，请直接输出本次验证码：%s", "SMS is not configured. Use this verification code: %s", "验证码"),
    systemMailNotConfiguredDevHint("3032", "系统未配置邮件服务，请直接输出本次验证码：%s", "Mail is not configured. Use this verification code: %s", "验证码"),
    systemApiKeyRateLimitPerMinute("4290", "每分钟请求次数超限", "Exceeded per-minute request frequency limit.", "API Key"),
    systemApiKeyRateLimitPerDay("4290", "每日请求次数超限", "Exceeded daily request frequency limit.", "API Key"),
    systemMailServiceNotConfigured("3033", "请在系统管理中配置邮件服务", "Configure mail service in system administration.", "邮件"),
    systemMailSendFailed("3034", "邮件发送异常，请检查邮件服务配置", "Failed to send email. Check mail service configuration.", "邮件"),
    systemSmsServiceNotConfigured("3035", "请在系统管理中配置短信服务", "Configure SMS service in system administration.", "短信"),
    systemIdGenerateRetryFailed("3036", "%s失败，请重试", "%s failed. Please try again.", "ID生成"),
    /** 与 UNAUTHORIZED 契约一致；建议 {@code BizException.of(HttpStatusEnum.UNAUTHORIZED, ErrorCodeEnum.UNAUTHORIZED, …)} */
    systemUnauthorizedOrSessionExpired("3037", "未登录或登录超时", "Not signed in or session expired.", "认证"),

    /** RBAC：角色 / 资源 / 用户组 domain 共用 */
    systemRbacCodeFormatInvalid("3080", "编码只能包含字母、数字和下划线，且必须以字母开头", "Code may only contain letters, digits and underscores, and must start with a letter.", "RBAC"),
    systemRbacResourceCodeFormatInvalid("3081", "资源码只能包含字母、数字和下划线，且必须以字母开头", "Resource code may only contain letters, digits and underscores, and must start with a letter.", "RBAC"),
    systemRbacCodeLengthExceeded("3082", "编码长度不能超过100", "Code length cannot exceed 100.", "RBAC"),
    systemRbacNameLengthExceeded("3083", "名称长度不能超过50", "Name length cannot exceed 50.", "RBAC"),
    systemRbacDescLengthExceeded("3084", "描述长度不能超过500", "Description length cannot exceed 500.", "RBAC"),
    systemRbacPathLengthExceeded("3085", "路径长度不能超过500", "Path length cannot exceed 500.", "RBAC"),
    systemRoleCodeDuplicate("3086", "已存在此角色编码", "This role code already exists.", "RBAC"),
    systemGroupCodeDuplicate("3087", "已存在此用户组编码", "This group code already exists.", "RBAC"),
    systemResourceCodeDuplicate("3088", "已存在此资源编码", "This resource code already exists.", "RBAC"),
    systemRbacSaveFailed("3089", "保存失败", "Save failed.", "RBAC"),
    systemRoleNotFound("3090", "角色不存在", "Role does not exist.", "RBAC"),
    systemResourceNotFound("3091", "资源不存在", "Resource does not exist.", "RBAC"),
    systemGroupNotFound("3092", "用户组不存在", "User group does not exist.", "RBAC"),
    systemBuiltinRoleCodeImmutable("3093", "系统内置角色编码不能修改", "Built-in role code cannot be changed.", "RBAC"),
    systemBuiltinRoleNameImmutable("3094", "系统内置角色名称不能修改", "Built-in role name cannot be changed.", "RBAC"),
    systemBuiltinRoleCannotDisable("3095", "系统内置角色不能禁用", "Built-in role cannot be disabled.", "RBAC"),
    systemBuiltinResourceCodeImmutable("3096", "系统内置资源编码不能修改", "Built-in resource code cannot be changed.", "RBAC"),
    systemBuiltinResourceNameImmutable("3097", "系统内置资源名称不能修改", "Built-in resource name cannot be changed.", "RBAC"),
    systemBuiltinResourceCannotDisable("3098", "系统内置资源不能禁用", "Built-in resource cannot be disabled.", "RBAC"),
    systemBuiltinGroupCodeImmutable("3099", "系统内置用户组编码不能修改", "Built-in group code cannot be changed.", "RBAC"),
    systemBuiltinGroupNameImmutable("3100", "系统内置用户组名称不能修改", "Built-in group name cannot be changed.", "RBAC"),
    systemBuiltinGroupCannotDisable("3101", "系统内置用户组不能禁用", "Built-in group cannot be disabled.", "RBAC"),
    systemRbacDataPermissionRequired("3102", "数据权限配置不能为空", "Data permission configuration is required.", "RBAC"),
    systemRbacTokenLimitMinInvalid("3103", "最大Token不能小于-1", "Max tokens cannot be less than -1.", "RBAC"),
    systemRoleBindRequiresAdminUser("3104", "仅管理员类型用户才可以绑定角色 [%s]", "Only admin-type users may bind role [%s].", "RBAC"),
    systemSuperAdminRequiresRoleMenuResources("3105", "超级管理员角色必须绑定必要 菜单[角色管理] 和 资源[查询、菜单权限]", "Super admin role must bind required menu [Role management] and resources [Query, menu permission].", "RBAC"),
    systemRbacMenuIdNotFound("3106", "菜单ID[%s]不存在", "Menu ID [%s] does not exist.", "RBAC"),
    systemSuperAdminRequiresRoleMenuResourcesAlt("3107", "超级管理员角色必须绑定必要 菜单[角色管理] 及资源 [查询、菜单权限]", "Super admin role must bind required menu [Role management] and resources [Query, menu permission].", "RBAC"),
    systemSuperAdminRequiresMenuByName("3108", "超级管理员角色必须绑定必要菜单 [%s]", "Super admin role must bind required menu [%s].", "RBAC"),
    systemSuperAdminResourceCodeMissing("3109", "超级管理员角色必须绑定必要菜单 [角色管理] 及资源 [查询、菜单权限]，系统未找到资源[%s]，请联系管理员检查配置", "Super admin must bind menu [Role management] and resources [Query, menu permission]. Resource [%s] not found. Contact an administrator.", "RBAC"),
    systemSuperAdminResourceMenuOrphan("3110", "超级管理员角色必须绑定必要菜单 [角色管理] 及资源 [查询、菜单权限]，资源[%s]未关联菜单，请联系管理员检查配置", "Super admin must bind menu [Role management] and resources [Query, menu permission]. Resource [%s] is not linked to a menu. Contact an administrator.", "RBAC"),
    systemSuperAdminBindIncomplete("3111", "超级管理员角色必须绑定必要菜单 [角色管理] 及资源 [查询、菜单权限]", "Super admin role must bind menu [Role management] and resources [Query, menu permission].", "RBAC"),
    systemRbacParentIdInvalid("3112", "父级ID无效", "Invalid parent ID.", "RBAC"),
    systemRbacParentResourceNotFoundWithParentId("3113", "父级资源不存在,parentId=%s", "Parent resource not found, parentId=%s", "RBAC"),
    systemRbacParentNameNotModule("3114", "[%s]不是模块，不能作为父级", "[%s] is not a module and cannot be used as a parent.", "RBAC"),
    systemRbacParentSelfReferenceForbidden("3115", "父级节点不能是自身 [id:%s]", "Parent node cannot be itself [id:%s].", "RBAC"),
    systemRbacParentResourceNotFound("3116", "父级资源不存在", "Parent resource does not exist.", "RBAC"),
    systemRbacParentIdInvalidForResource("3117", "父级ID无效: resourceId=%s", "Invalid parent ID: resourceId=%s", "RBAC"),
    systemRbacParentNodeNotFound("3118", "父级节点不存在 [parentId:%s]", "Parent node does not exist [parentId:%s].", "RBAC"),
    systemResourceTreeJsonInvalid("3119", "resourceTreeJson 反序列化失败", "Failed to deserialize resourceTreeJson.", "RBAC"),
    systemRoleNotFoundWithRowId("3120", "角色不存在: id=%s", "Role does not exist: id=%s", "RBAC"),
    systemRbacUserNotFoundWithId("3121", "用户不存在,id=%s", "User does not exist, id=%s", "RBAC"),
    systemRoleNotFoundWithRoleId("3122", "角色不存在,id=%s", "Role does not exist, id=%s", "RBAC"),
    systemGroupMaxUsersBelowBound("3123", "最大用户数不能小于已绑定用户数，当前已绑定%s人", "Max users cannot be below the number already bound; currently %s user(s) bound.", "RBAC"),
    systemGroupUserLimitExceeded("3124", "组用户数量超出限制", "Group user count exceeds the limit.", "RBAC"),
    systemGroupNotFoundWithRowId("3125", "用户组不存在: id=%s", "User group does not exist: id=%s", "RBAC"),
    systemGroupNotFoundWithGroupId("3126", "组不存在,id=%s", "Group does not exist, id=%s", "RBAC"),
    systemGroupNotFoundWithGroupIdAlt("3127", "用户组不存在,id=%s", "User group does not exist, id=%s", "RBAC"),
    systemDataPermissionTargetTypeInvalid("3128", "数据权限目标类型错误", "Invalid data permission target type.", "数据权限"),
    systemDataPermissionTargetIdInvalid("3129", "数据权限目标ID错误", "Invalid data permission target ID.", "数据权限"),
    systemMenuBindResourceNotFound("3130", "资源ID[%s]不存在", "Resource ID [%s] does not exist.", "菜单绑定"),
    systemMenuBindResourceOutOfScope("3131", "资源ID[%s]不在菜单ID[%s]的绑定资源范围内", "Resource ID [%s] is outside the bound resources for menu ID [%s].", "菜单绑定"),
    systemMenuBindResourceBindTypeInvalid("3132", "资源ID[%s]的绑定类型[%s]无效，只能是0(NONE)、1(ALL)或2(PART)", "For resource ID [%s], bind type [%s] is invalid; must be 0 (NONE), 1 (ALL), or 2 (PART).", "菜单绑定"),
    systemRbacResourceCodeLengthExceeded("3133", "资源码长度不能超过100", "Resource code length cannot exceed 100.", "RBAC"),
    systemGroupCannotBindForbiddenMenu("3134", "用户组不能绑定「%s」菜单", "User group cannot bind menu \"%s\".", "RBAC"),
    systemVerifyCodeIncorrect("3135", "验证码错误", "Incorrect verification code.", "验证码"),
    systemVerifyParamInvalid("3136", "校验参数异常", "Invalid verification parameters.", "验证码"),
    systemVerifyCodeCheckFailed("3137", "验证码校验失败", "Verification code check failed.", "验证码"),
    systemUsernameDigitsOnlyForbidden("3138", "用户名不能为纯数字", "Username cannot be all digits.", "用户"),
    systemUsernameAlreadyInUse("3139", "用户名已被占用", "Username is already taken.", "用户"),
    systemUsernameFormatInvalid("3140", "用户名不符合规范", "Username does not meet the rules.", "用户"),
    systemUsernameChangeDisallowedInCurrentAuthMode("3141", "当前认证模式不允许修改用户名", "Username cannot be changed in the current auth mode.", "用户"),
    systemNicknameDigitsOnlyForbidden("3142", "昵称不能为纯数字", "Nickname cannot be all digits.", "用户"),
    systemWeChatAccessTokenFetchFailed("3143", "获取微信 access_token 失败", "Failed to obtain WeChat access_token.", "微信"),
    systemWeChatApiReturnedError("3144", "%s", "%s", "微信"),
    systemWeChatPhoneNumberFetchFailed("3145", "获取微信手机号失败", "Failed to obtain WeChat phone number.", "微信"),
    systemTenantDomainAlreadyInUse("3146", "域名%s已被占用", "Domain %s is already in use.", "租户"),
    systemUserIdInvalid("3147", "错误的用户ID", "Invalid user ID.", "用户"),
    systemMenuPermissionImportTenantInvalid("3148", "菜单权限导入失败,租户ID无效", "Menu permission import failed: invalid tenant ID.", "权限"),
    systemMenuPermissionDiffImportTenantInvalid("3149", "菜单权限差异导入失败,租户ID无效", "Menu permission diff import failed: invalid tenant ID.", "权限"),
    systemCategoryOperationDenied("3150", "无权限操作该分类", "No permission to operate this category.", "分类"),
    systemMenuIdNullWithNodeName("3151", "菜单id不能为null,name:%s", "Menu id cannot be null, name:%s", "菜单"),
    systemI18nExportRowCountExceeded("3152", "导出行数（%d）超过上限（%d），请缩小筛选条件后重试", "Export row count (%d) exceeds the limit (%d). Narrow filters and try again.", "i18n"),
    systemI18nTranslationFailedTargetLang("3153", "翻译失败。目标语言：%s", "Translation failed. Target language: %s", "i18n"),
    systemI18nBatchTranslationSizeMismatch("3154", "批量翻译返回条数不匹配。目标语言：%s，分块起始：%s", "Batch translation count mismatch. Target language: %s, chunk start: %s", "i18n"),
    systemI18nBatchTranslationResultEmpty("3155", "批量翻译结果为空。Key = %s，目标语言 = %s", "Batch translation result is empty. Key = %s, target language = %s", "i18n"),
    systemI18nLangTagInvalid("3156", "语言标识格式不正确，请使用合法的语言标签，如 zh-CN、en-US、zh-Hans-CN", "Invalid language tag. Use a valid BCP 47 tag such as zh-CN, en-US, or zh-Hans-CN.", "i18n"),
    systemI18nLangTagDuplicate("3157", "该语言标签已存在，不允许重复", "This language tag already exists; duplicates are not allowed.", "i18n"),
    systemI18nBatchTranslationNotJson("3158", "批量翻译返回非 JSON 对象：%s", "Batch translation returned a non-JSON object: %s", "i18n"),
    systemI18nBatchTranslationKeyOrValueMissing("3159", "批量翻译缺少 key 或值为空: %s", "Batch translation missing key or empty value: %s", "i18n"),
    systemI18nTranslationEmpty("3160", "翻译返回空结果", "Translation returned empty.", "i18n"),
    systemI18nTranslationModelAuthFailed("3161", "翻译失败：模型鉴权失败，请检查默认模型的 API Key/鉴权配置。", "Translation failed: model authentication error. Check default model API key and auth settings.", "i18n"),
    systemI18nTranslationFailedWithReason("3162", "翻译失败: %s", "Translation failed: %s", "i18n"),
    systemI18nOriginalRecordNotFound("3163", "原始记录不存在", "The original record does not exist.", "i18n"),

    bootstrapAuthRedirectUrl("3164", "%s", "%s", "登录跳转"),
    bootstrapLicenseContentInvalid("3165", "许可证内容无效", "Invalid license content.", "License"),
    systemNoPermissionForSystemApi("3166", "你没有权限", "You do not have permission.", "权限"),
    apiKeyInvalid("3167", "无效的 API Key", "Invalid API Key.", "API Key"),
    apiKeyExpired("3168", "API Key 已过期", "API Key expired.", "API Key"),
    apiKeyAccessDenied("3169", "API Key 无访问权限", "API Key does not have access permissions.", "API Key"),
    apiKeyMissing("3170", "缺少 API Key", "Missing API Key.", "API Key"),
    apiKeyUserDisabled("3171", "用户已停用", "User disabled.", "API Key"),
    apiKeyAgentApiDisabled("3172", "当前已禁用 API 调用", "The API calls are currently disabled.", "API Key"),
    apiKeyOpenApiNotFound("3173", "API 不存在或无权限", "API not found or permission denied.", "API Key"),
    apiKeyPermissionDenied("3174", "无权限", "Permission denied.", "API Key"),

    imFeishuWebhookMissingAppId("3178", "飞书 Webhook 缺少必要参数: appId", "Feishu Webhook is missing required parameter: appId.", "IM"),
    imFeishuBotNotBound("3179", "飞书机器人未绑定", "Feishu bot is not bound.", "IM"),
    imDingtalkWebhookMissingRobotCode("3180", "钉钉 Webhook 缺少必要参数: robotCode", "DingTalk Webhook is missing required parameter: robotCode.", "IM"),
    imDingtalkBotNotBound("3181", "钉钉机器人未绑定", "DingTalk bot is not bound.", "IM"),
    imWechatQrFetchFailed("3182", "获取微信二维码失败: %s", "Failed to fetch WeChat QR code: %s", "IM"),
    imWechatQrSessionExpired("3183", "扫码会话已过期或不存在", "Scan session has expired or does not exist.", "IM"),
    imWechatQrSessionDataInvalid("3184", "会话数据异常", "Session data is invalid.", "IM"),
    imWechatQrQueryStatusFailed("3185", "查询扫码状态失败: %s", "Failed to query scan status: %s", "IM"),
    imWechatIlinkChannelOnly("3188", "仅支持微信 iLink 渠道配置", "Only WeChat iLink channel configuration is supported.", "IM"),
    imWechatIlinkConfigDisabled("3189", "当前微信 iLink 配置未启用", "WeChat iLink configuration is not enabled.", "IM"),
    imWechatIlinkConfigMissing("3190", "微信 iLink 配置缺失", "WeChat iLink configuration is missing.", "IM"),
    imWechatIlinkBotTokenMissing("3191", "微信 iLink 配置缺少 botToken", "WeChat iLink configuration is missing botToken.", "IM"),
    imWechatIlinkUserIdMissing("3192", "微信 iLink 配置缺少 ilinkUserId", "WeChat iLink configuration is missing ilinkUserId.", "IM"),
    imWechatIlinkPushFailed("3193", "推送失败: %s", "Push failed: %s", "IM"),
    imChannelConfigInvalidOrUnavailable("3194", "指定的 im_channel_config 不存在、未启用或不是当前空间下可用的微信 iLink 渠道", "The specified im_channel_config does not exist, is disabled, or is not an available WeChat iLink channel in this space.", "IM"),
    imNoWechatIlinkInSpace("3195", "当前空间未配置可用的微信 iLink 渠道", "No available WeChat iLink channel is configured for this space.", "IM"),
    imMultipleWechatIlinkNeedExplicitId("3196", "存在多条启用的微信 iLink 配置，主动/定时任务须显式指定 im_channel_config.id（对齐 openclaw-weixin 1.0.3 delivery.accountId）", "Multiple enabled WeChat iLink configs exist; proactive/scheduled tasks must specify im_channel_config.id explicitly (aligned with openclaw-weixin 1.0.3 delivery.accountId).", "IM"),
    imTenantOrUserMissing("3197", "租户或用户信息缺失", "Tenant or user information is missing.", "IM"),
    imWechatChannelNotFoundForBot("3198", "未找到与该 botId 对应的微信渠道配置", "No WeChat channel configuration found for this botId.", "IM"),
    imWechatChannelNotFoundForUser("3199", "未找到当前用户的微信渠道配置", "No WeChat channel configuration found for the current user.", "IM"),
    imWechatChannelDisabled("3200", "微信渠道配置已禁用", "WeChat channel configuration is disabled.", "IM"),
    imWechatIlinkParseFailed("3201", "微信 iLink 配置解析失败", "Failed to parse WeChat iLink configuration.", "IM"),
    imTenantFetchFailed("3202", "获取租户信息失败", "Failed to fetch tenant information.", "IM"),
    imCannotResolveTargetId("3207", "无法从配置数据中解析目标唯一标识", "Cannot resolve target unique identifier from configuration data.", "IM"),
    imChannelConfigDuplicate("3208", "该渠道配置已存在", "This channel configuration already exists.", "IM"),
    imChannelConfigDuplicateDetail("3209", "该渠道配置已存在: %s %s %s", "This channel configuration already exists: %s %s %s", "IM"),
    customPageMultimodalModelUnavailable("3212", "当前多模态模型不可用：%s", "Multimodal model is unavailable: %s", "自定义页面"),
    customPageModelNotMultimodal("3213", "当前模型不支持多模态，无法解析图片，模型 id=%s", "This model does not support multimodal input; cannot parse images. Model id=%s", "自定义页面"),
    customPageChatModelUnavailable("3214", "当前聊天模型不可用：%s", "Chat model is unavailable: %s", "自定义页面"),
    customPageProxyProjectBuildNotFound("3215", "未找到项目构建信息", "Project build information not found.", "自定义页面"),
    customPageProxyDevServerNotStarted("3216", "项目未启动开发服务器", "Dev server has not been started for this project.", "自定义页面"),
    customPageProxyAuthFailed("3217", "认证失败", "Authentication failed.", "自定义页面"),
    customPageProxyNoSpace("3218", "无空间信息", "No space information.", "自定义页面"),
    customPageProxyNoAgentPermission("3219", "无Agent权限", "No Agent permission.", "自定义页面"),
    customPageProxyNoAgentOrchestrationPermission("3220", "无Agent编排权限", "No Agent orchestration permission.", "自定义页面"),

    sandboxClientAddressUnavailable("3222", "无法获取客户端服务地址", "Unable to obtain client service address.", "沙盒"),
    sandboxUserProxyCreateFailed("3223", "创建用户沙盒代理失败", "Failed to create user sandbox proxy.", "沙盒"),
    sandboxDeployFailedWithHelp("3225", "%s", "%s", "沙盒"),
    sandboxConfigKeyDuplicate("3226", "配置键已存在，请使用其他配置键", "Configuration key already exists; use another key.", "沙盒"),

    mcpNotFound("3227", "MCP不存在", "MCP does not exist.", "MCP"),
    mcpServiceConfigJsonInvalid("3228", "服务配置格式错误，请填写正确的JSON数据", "Invalid service configuration format; provide valid JSON.", "MCP"),
    mcpNpxConfigInvalid("3229", "请输入正确的npx配置", "Enter a valid npx configuration.", "MCP"),
    mcpUvxConfigInvalid("3230", "请输入正确的uvx配置", "Enter a valid uvx configuration.", "MCP"),
    mcpStreamableHttpConfigInvalid("3231", "请输入正确的streamableHTTP配置", "Enter a valid streamable HTTP configuration.", "MCP"),
    mcpSseConfigInvalid("3232", "请输入正确的sse配置", "Enter a valid SSE configuration.", "MCP"),
    /** MCP / 插件参数校验共用 */
    paramArgTypeInvalid("3234", "参数[%s]类型错误", "Parameter [%s] has an invalid type.", "参数"),
    mcpDeployResponseNull("3235", "McpDeployStatusResponse 为空", "McpDeployStatusResponse is null.", "MCP"),
    remoteServiceMessage("3236", "%s", "%s", "远程调用"),

    customPageDomainBindPermissionDenied("3237", "无权限操作该域名绑定", "No permission to manage this domain binding.", "自定义页面"),
    customPageProxyEnvPathExists("3238", "指定环境和路径的代理配置已存在，无法添加", "Proxy config for this environment and path already exists; cannot add.", "自定义页面"),
    customPageProxyEnvPathNotFoundForEdit("3239", "指定环境和路径的代理配置不存在，无法编辑", "Proxy config for this environment and path does not exist; cannot edit.", "自定义页面"),
    customPageProxyEnvPathNotFoundForDelete("3240", "指定环境和路径的代理配置不存在，无法删除", "Proxy config for this environment and path does not exist; cannot delete.", "自定义页面"),
    customPagePathConfigExists("3241", "指定路径的配置已存在，无法添加", "Configuration for this path already exists; cannot add.", "自定义页面"),
    customPagePathConfigNotFoundForEdit("3242", "指定路径的配置不存在，无法编辑", "Configuration for this path does not exist; cannot edit.", "自定义页面"),
    customPagePathConfigNotFoundForDelete("3243", "指定路径的配置不存在，无法删除", "Configuration for this path does not exist; cannot delete.", "自定义页面"),
    customPageProjectConfigNotFound("3244", "项目配置不存在", "Project configuration does not exist.", "自定义页面"),
    customPageDuplicatePathConfig("3245", "存在重复的路径配置: %s:%s", "Duplicate path configuration: %s:%s", "自定义页面"),
    customPageBackendListEmpty("3246", "后端地址列表不能为空: %s:%s", "Backend address list cannot be empty: %s:%s", "自定义页面"),
    customPageBackendAddressEmpty("3247", "后端地址不能为空: %s:%s", "Backend address cannot be empty: %s:%s", "自定义页面"),
    customPagePluginQueryFailed("3248", "查询插件失败,插件[%s:%s]", "Failed to query plugin [%s:%s]", "自定义页面"),
    customPageWorkflowQueryFailed("3249", "查询工作流失败,工作流[%s:%s]", "Failed to query workflow [%s:%s]", "自定义页面"),
    customPageDatasourceParamNameDuplicate("3251", "存在重复的参数名称: %s", "Duplicate parameter name: %s", "自定义页面"),
    customPageConfigFileParseFailed("3252", "配置文件解析失败: %s", "Failed to parse configuration file: %s", "自定义页面"),
    customPageWebAppCountExceeded("3253", "你的网页应用数量已经达到上限，网页应用上限数为%s", "You have reached the web app limit; maximum is %s.", "自定义页面"),
    customPageCreateConfigFailed("3254", "创建自定义页面(config)失败: %s", "Failed to create custom page (config): %s", "自定义页面"),
    customPageCreateBuildFailed("3255", "创建自定义页面(build)失败: %s", "Failed to create custom page (build): %s", "自定义页面"),
    customPageCreateAgentFailed("3256", "创建智能体失败: %s", "Failed to create agent: %s", "自定义页面"),
    customPageBindAgentFailed("3257", "绑定智能体到项目失败: %s", "Failed to bind agent to project: %s", "自定义页面"),
    customPageCreateReverseProxyFailed("3258", "创建反向代理项目失败: %s", "Failed to create reverse proxy project: %s", "自定义页面"),
    customPageDeleteReverseProxyFailed("3259", "删除反向代理配置失败: %s", "Failed to delete reverse proxy configuration: %s", "自定义页面"),
    customPageConfigPageParamsFailed("3260", "配置页面参数失败: %s", "Failed to configure page parameters: %s", "自定义页面"),
    customPageAddPathConfigFailed("3261", "添加路径配置失败: %s", "Failed to add path configuration: %s", "自定义页面"),
    customPageEditPathConfigFailed("3262", "编辑路径配置失败: %s", "Failed to edit path configuration: %s", "自定义页面"),
    customPageDeletePathConfigFailed("3263", "删除路径配置失败: %s", "Failed to delete path configuration: %s", "自定义页面"),
    customPageBatchReverseProxyFailed("3264", "批量配置反向代理失败: %s", "Failed to batch configure reverse proxy: %s", "自定义页面"),
    customPageSaveDataSourceFailed("3265", "保存数据源失败: %s", "Failed to save data source: %s", "自定义页面"),
    customPageUnbindDataSourceFailed("3266", "解绑数据源失败: %s", "Failed to unbind data source: %s", "自定义页面"),
    customPageUpdateProjectFailed("3267", "修改项目失败: %s", "Failed to update project: %s", "自定义页面"),
    customPageUpdateAgentFailed("3268", "更新智能体失败: %s", "Failed to update agent: %s", "自定义页面"),
    customPageUpdateProjectException("3269", "修改项目异常: %s", "Error while updating project: %s", "自定义页面"),
    customPageDeleteProjectFailed("3270", "删除项目失败: %s", "Failed to delete project: %s", "自定义页面"),
    customPageDeleteAgentFailed("3271", "删除智能体失败: %s", "Failed to delete agent: %s", "自定义页面"),
    customPageDeleteProjectException("3272", "删除项目异常: %s", "Error while deleting project: %s", "自定义页面"),
    customPageCopyPluginFailed("3273", "复制插件失败: %s", "Failed to copy plugin: %s", "自定义页面"),
    customPageCopyWorkflowFailed("3274", "复制工作流失败: %s", "Failed to copy workflow: %s", "自定义页面"),
    customPageProxyPathLoadFailed("3275", "获取页面配置失败", "Failed to load page configuration.", "自定义页面"),
    customPageProxyPathNoAgent("3277", "页面没有绑定智能体", "No agent is bound to this page.", "自定义页面"),
    customPageKeepAliveDbUpdateFailed("3278", "KeepAlive更新库表失败", "KeepAlive failed to update database tables.", "自定义页面"),

    //加密解密异常
    cipherDecryptFailed("4001", "解密失败", "Decryption failed.", "解密失败"),
    cipherEncryptFailed("4002", "加密失败", "Encryption failed.", "加密失败"),

    //知识库
    knowledgeTemplateDirectiveTypeNotFound("5002", "模板指令类型不存在", "Template directive type does not exist.", "模板指令类型不存在"),
    knowledgeUnknownAnalysisDimension("5005", "未识别的分析维度类型[%s]", "Unknown analysis dimension type [%s].", "未识别的分析维度类型"),
    knowledgeDataMappingFailed("5006", "数据映射识别,异常=%s", "Data mapping failed, error=%s", "excel数据映射记录"),
    knowledgeExcelDataRequired("5007", "Excel相关数据不能为空", "Excel-related data cannot be empty.", "Excel相关数据不能为空"),
    knowledgeExcelHeaderRequired("5008", "Excel抬头字段信息不能为空", "Excel header field information cannot be empty.", "Excel抬头字段信息不能为空"),
    knowledgeVectorDatabaseNotFound("5011", "向量数据库[{}]不存在", "Vector database [{}] does not exist.", ""),
    knowledgeFileIdNotFound("5012", "文件ID不存在", "File ID does not exist.", ""),
    knowledgeDocumentParseFailed("5014", "解析文档失败", "Failed to parse document.", ""),
    knowledgeDocumentUnsupportedType("5015", "解析文档失败,错误:不支持的文件类型", "Failed to parse document: unsupported file type.", ""),
    knowledgeLlmAnswerEmpty("5016", "大模型返回的答案为空,分段id=%s", "The model returned an empty answer, segment id=%s", ""),
    knowledgeLlmQuestionEmpty("5017", "大模型返回的问题为空,分段id=%s", "The model returned an empty question, segment id=%s", ""),
    knowledgeImportFileFailed("5019", "导入文件失败,%s", "Failed to import file, %s", ""),
    knowledgeGenerateTemplateFailed("5020", "生成模板失败：,%s", "Failed to generate template: %s", ""),
    knowledgeKbNotFoundById("5021", "知识库不存在,知识库ID=%s", "Knowledge base does not exist, id=%s", ""),  
    knowledgeVectorizationFailed("5022", "向量化失败,%s", "Vectorization failed, %s", ""),
    knowledgeDeleteKbFulltextFailed("5023", "删除知识库全文检索数据失败", "Failed to delete knowledge base full-text index data.", ""),
    knowledgeDeleteDocFulltextFailed("5024", "删除文档全文检索数据失败", "Failed to delete document full-text index data.", ""),
    knowledgeDeleteSegmentFulltextFailed("5025", "删除原始分段全文检索数据失败", "Failed to delete original segment full-text index data.", ""),
    knowledgeJsonParseUnsupported("5026", "解析JSON文档失败,JSON格式不支持,期望JSON数组或JSON对象", "Failed to parse JSON document: unsupported format; expected a JSON array or object.", ""),
    knowledgeQaGenerationBusy("5027", "操作失败：当前数据正在生成问答，请稍后重试！", "Operation failed: Q&A generation is in progress for this data. Please try again later.", "知识库"),
    knowledgeStorageUpperBound("5028", "操作失败，已超过知识库的存储上限！(最大%sGB)", "Operation failed: knowledge base storage limit exceeded (max %s GB).", "知识库"),
    knowledgeKbCreateCountExceeded("5029", "操作失败，添加的知识库数量超过上限（%s）", "Operation failed: number of knowledge bases exceeds the limit (%s).", "知识库"),
    knowledgeNotFoundSimple("5030", "知识库不存在", "Knowledge base does not exist.", "知识库"),
    memoryUnitNotFound("5031", "记忆单元不存在: %s", "Memory unit does not exist: %s", "记忆"),
    modelProxyTokenLimitExceeded("5032", "超出 token 限制", "Token limit exceeded.", "模型代理"),

    //组件模块
    composeCannotGetCreateTableDdl("6002", "无法获取建表DDL语句", "Unable to obtain CREATE TABLE DDL.", ""),
    composeDorisDbNameParseFailed("6003", "解析Doris数据库名称失败: %s", "Failed to parse Doris database name: %s", ""),
    composeSqlOnlyDmlAllowed("6004", "只允许执行 SELECT/INSERT/UPDATE/DELETE 查询语句", "Only SELECT, INSERT, UPDATE, or DELETE statements are allowed.", ""),
    composeSqlEmpty("6005", "执行的SQL语句不能为空", "SQL statement cannot be empty.", ""),
    composeSqlExecuteFailed("6006", "执行SQL失败,%s", "SQL execution failed, %s", ""),
    composeCreateTableFailed("6008", "创建表失败", "Failed to create table.", ""),
    composeCannotBuildUpdateSet("6010", "无法构建更新的 SET 子句", "Unable to build UPDATE SET clause.", ""),
    composeUpdateDataEmpty("6011", "更新的数据不能为空", "Update data cannot be empty.", ""),
    composeSqlParseFailed("6015", "SQL解析失败,%s", "SQL parse failed, %s", ""),
    composeSqlOnlyDdl("6016", "只允许DDL语句,sql=%s", "Only DDL statements are allowed, sql=%s", ""),
    composeQueryAllDataFailed("6017", "查询全部数据失败", "Failed to query all data.", ""),
    composeCannotDropFieldWithData("6018", "表中已有数据，不允许删除字段", "Cannot drop column: table already contains data.", ""),
    composeCannotChangeUniqueWithData("6019", "字段[%s]已有数据，不允许修改唯一性约束", "Cannot change unique constraint on field [%s]: data already exists.", ""),
    composeCannotChangeNullableWithData("6020", "字段[%s]已有数据，不允许修改非空约束", "Cannot change nullability on field [%s]: data already exists.", ""),
    composeDbTypeNotConfigured("6021", "未配置数据库类型,配置:spring.datasource.sql-generator.type", "Database type not configured; set spring.datasource.sql-generator.type.", ""),
    composeUnsupportedDbType("6022", "不支持的数据库类型: %s, 仅支持 mysql 或 doris", "Unsupported database type: %s; only mysql or doris is supported.", ""),
    composeDorisUrlNotConfigured("6023", "未配置Doris数据源URL,配置:spring.datasource.dynamic.datasource.doris.url", "Doris datasource URL not configured; set spring.datasource.dynamic.datasource.doris.url.", ""),
    composeInsertDataEmpty("6024", "插入的数据不能为空", "Insert data cannot be empty.", ""),
    composeTableDefinitionNotFound("6025", "表定义不存在", "Table definition does not exist.", ""),
    composeCreateIndexFailed("6026", "创建索引失败", "Failed to create index.", ""),
    composeFieldNameTooLong("6028", "字段名长度不能超过64字符", "Field name cannot exceed 64 characters.", ""),
    composeFieldNameMustStartWithLetter("6029", "字段名必须以英文字母开头", "Field name must start with a letter.", ""),
    composeFieldNameInvalidChars("6030", "字段名只能包含字母、数字和下划线", "Field name may only contain letters, digits, and underscores.", ""),
    composeCheckTableExistsFailed("6031", "检查表是否存在时发生错误，数据库,%s", "Error while checking if table exists, database %s", ""),
    composeTruncateTableFailed("6032", "清空表数据时发生错误，数据库,%s", "Error while truncating table, database %s", ""),
    composeGetTableDefinitionFailed("6033", "获取表定义信息时发生错误，数据库,%s", "Error while fetching table definition, database %s", ""),
    composeRawSqlExecuteFailed("6034", "执行原始管理/DML/DDL的SQL异常,%s", "Error executing raw admin/DML/DDL SQL, %s", ""),
    composeUnsupportedSqlType("6035", "不支持的SQL类型,SqlType=%s", "Unsupported SQL type, SqlType=%s", ""),
    composeBuildConditionFailed("6036", "创建条件表达式失败,%s", "Failed to build condition expression, %s", ""),
    composeDefaultValueMustBeNumber("6037", "字段[%s]的默认值必须为数值", "Default value for field [%s] must be numeric.", ""),
    composeDefaultValueMustBeBoolean("6038", "字段[%s]的默认值必须为布尔值", "Default value for field [%s] must be boolean.", ""),
    composeDefaultValueTooLong("6039", "字段[%s]的默认值长度不能超过255字符", "Default value for field [%s] cannot exceed 255 characters.", ""),
    composeMediumtextNoDefault("6040", "MEDIUMTEXT类型字段[%s]不允许设置默认值", "MEDIUMTEXT field [%s] cannot have a default value.", "MEDIUMTEXT类型字段不允许设置默认值"),
    composeExcelRowCountExceeded("6041", "Excel数据行数超过限制,最大支持[%s]行", "Excel row count exceeds limit; maximum [%s] rows.", ""),
    composeTableRowCountExceeded("6042", "表总行数超过限制,最大支持[%s]行", "Total table row count exceeds limit; maximum [%s] rows.", ""),
    composeTableDefMissingFields("6043", "表定义缺少字段定义", "Table definition is missing field definitions.", ""),
    composeFieldAlreadyExists("6044", "字段[%s]已存在", "Field [%s] already exists.", ""),
    composeDefaultValueOutOfRange("6045", "字段[%s]的默认值超出范围,范围区间:[%s,%s]", "Default value for field [%s] is out of range [%s, %s].", ""),
    composeGenericMessage("6047", "%s", "%s", ""),



    //日志平台
    logPlatformSearchFailed("7001", "搜索失败,%s", "Search failed, %s", "搜索失败"),
    logPlatformInsertFailed("7002", "新增失败,%s", "Insert failed, %s", "新增失败"),
    logPlatformBatchInsertFailed("7003", "批量新增失败,%s", "Batch insert failed, %s", "批量新增失败"),

    //生态市场
    ecoMarketGetConfigFailed("8002", "获取配置异常,%s", "Failed to fetch configuration, %s", "获取配置详情异常"),
    ecoMarketPublishConfigFailed("8003", "发布配置异常,%s", "Failed to publish configuration, %s", "发布配置异常"),
    ecoMarketOfflineConfigFailed("8004", "下线配置异常,%s", "Failed to offline configuration, %s", "下线配置异常"),
    ecoMarketQueryConfigStatusFailed("8005", "查询配置状态异常,%s", "Failed to query configuration status, %s", "查询配置状态异常"),
    ecoMarketQueryPublishedDetailFailed("8006", "查询发布配置详情异常,%s", "Failed to query published configuration detail, %s", "查询发布配置详情异常"),
    ecoMarketCannotDeleteRemotePublished("8010", "远程生态市场已上架的配置不能删除", "Cannot delete configuration that is listed on the remote marketplace.", ""),
    ecoMarketClientSecretFetchFailed("8011", "获取客户端密钥失败，请稍后重试", "Failed to fetch client secret. Please try again later.", "获取客户端密钥失败"),
    ecoMarketUpdateOnlyDraftOrRejected("8012", "只能更新草稿或被驳回状态的配置", "Only draft or rejected configurations can be updated.", "只能更新草稿或被驳回状态的配置"),
    ecoMarketNoPermissionToUpdate("8013", "无权更新此配置", "No permission to update this configuration.", "无权更新此配置"),
    ecoMarketConfigInfoNotFound("8014", "未找到对应的配置信息", "Configuration not found.", "未找到对应的配置信息"),
    ecoMarketModelAndUidRequired("8016", "配置模型不能为空且UID必须指定", "Model is required and UID must be specified.", "配置模型不能为空且UID必须指定"),
    ecoMarketPublishedConfigNotFound("8017", "未找到对应的发布配置信息", "Published configuration not found.", "未找到对应的发布配置信息"),
    ecoMarketUnsupportedDataType("8019", "不支持的数据类型", "Unsupported data type.", ""),
    ecoMarketReleaseFailed("8020", "发版失败,%s", "Release failed, %s", ""),
    ecoMarketSaveConfigFailed("8021", "保存配置异常,%s", "Failed to save configuration, %s", ""),
    ecoMarketEnableConfigFailed("8023", "启用配置失败", "Failed to enable configuration.", ""),
    ecoMarketDuplicateShareNotAllowed("8025", "已有重复的配置,不允许新建我的分享", "Duplicate configuration exists; cannot create a new share.", ""),
    ecoMarketCenterUpgrading("8026", "生态市场中心服务升级中，请稍后再试", "Eco marketplace center is upgrading. Please try again later.", ""),
    ecoMarketConfigResultBodyEmpty("8027", "获取配置结果失败,Body为空", "Failed to get configuration result: empty body.", ""),
    ecoMarketDeployMcpFailed("8030", "部署MCP失败", "Failed to deploy MCP.", "部署MCP失败"),
    ecoMarketStopMcpFailed("8031", "停止MCP失败", "Failed to stop MCP.", "停止MCP失败"),
    ecoMarketMcpConfigParseFailed("8032", "MCP配置解析失败", "Failed to parse MCP configuration.", "MCP配置解析失败"),
    ecoMarketDisableConfigFailed("8033", "禁用配置失败", "Failed to disable configuration.", ""),
    ecoMarketOfflineOnlyPublishedOrReviewing("8034", "只有已发布/审核中状态的配置可以下线", "Only published or under-review configurations can be taken offline.", ""),
    ecoMarketOfflineServerConfigFailed("8035", "下线服务器配置失败，请稍后重试", "Failed to offline server configuration. Please try again later.", ""),
    ecoMarketNotPublishedNoOffline("8036", "未发布,无需下线", "Not published; no need to offline.", ""),
    ecoMarketRevokeOnlyReviewing("8037", "只有审核中状态的配置可以撤销发布", "Only under-review configurations can be revoked from publication.", ""),
    ecoMarketCannotShareFromMarket("8038", "禁止分享生态市场获取的配置", "Sharing configurations obtained from the marketplace is not allowed.", ""),
    ecoMarketAgentPageRequiredForShare("8039", "智能体未绑定页面,不能分享为应用页面", "Agent is not bound to a page; cannot share as an app page.", ""),
    ecoMarketPageExportFailed("8040", "页面导出失败", "Failed to export page.", ""),
    ecoMarketPageArchiveDownloadFailed("8042", "下载页面压缩包失败", "Failed to download page archive.", ""),
    ecoMarketPageProjectCreateFailed("8043", "创建页面项目失败", "Failed to create page project.", ""),
    ecoMarketPageArchiveUploadFailed("8044", "上传页面压缩包失败", "Failed to upload page archive.", ""),
    ecoMarketPagePublishFailed("8045", "发布页面失败", "Failed to publish page.", ""),
    ecoMarketAppPageEnableFailed("8046", "应用页面启用失败", "Failed to enable app page.", ""),
    ecoMarketDeleteOnlyOwnShare("8047", "只能删除自己分享的配置", "You can only delete configurations you shared.", ""),


    //AI 开发自定义页面
    customPageAgentTaskInProgress("9010", "Agent正在执行任务，请等待当前任务完成后再发送新请求", "Agent is running a task; wait for it to finish before sending another request.", "Agent正在执行任务，请等待当前任务完成后再发送新请求;前端全局处理了这个错误码"),

    /** 智能体模块内部/防御性：仅英文提示，不做多语言业务文案 */
    agentDependencyServiceError("9198", "依赖服务返回错误", "The dependency service returned an error.", "RPC/内部透传"),

    // 智能体 Agent 模块（9200–9499）
    agentWorkflowIdInvalid("9201", "workflowId错误", "Invalid workflowId.", "参数"),
    agentWorkflowHasInvalidNodesForPublish("9202", "工作流存在错误节点，不允许发布，请重新试运行", "Workflow has invalid nodes; publishing is not allowed. Re-run and fix.", "工作流"),
    agentWorkflowCyclicDependency("9203", "你添加的节点存在工作流循环依赖，请重新选择", "The nodes you added create a cyclic dependency; choose again.", "工作流"),
    agentTableIdInvalid("9204", "表ID错误", "Invalid table ID.", "参数"),
    agentKnowledgeBaseRemovedOrMissing("9205", "知识库[%s]不存在或已删除，请移除", "Knowledge base [%s] does not exist or was removed; remove it.", "工作流/知识库"),
    agentWorkflowNodeIdInvalid("9206", "节点ID错误", "Invalid node ID.", "参数"),
    agentWorkflowNotFound("9207", "Workflow不存在", "Workflow does not exist.", "工作流"),
    agentIdInvalid("9208", "agentId错误", "Invalid agentId.", "参数"),
    agentModelComponentCannotAddManually("9209", "模型组件配置不能手动添加", "Model component cannot be added manually.", "智能体组件"),
    agentPluginNotFoundOrUnpublished("9210", "插件不存在或未发布", "Plugin does not exist or is not published.", "组件"),
    agentWorkflowNotFoundOrUnpublished("9211", "工作流不存在或未发布", "Workflow does not exist or is not published.", "组件"),
    agentMcpConfigIncomplete("9213", "MCP缺少必要配置参数", "MCP is missing required configuration.", "组件"),
    agentSkillNotFoundOrUnpublished("9214", "技能不存在或未发布", "Skill does not exist or is not published.", "组件"),
    agentModelComponentCannotDelete("9216", "模型组件配置不能删除", "Model component cannot be deleted.", "组件"),
    agentBoundModelOffline("9217", "智能体关联大模型已下线，请重新配置", "The bound LLM is offline; reconfigure the agent.", "智能体"),
    agentNotPublishedOrOffline("9218", "该智能体未发布或已下架", "This agent is not published or has been taken offline.", "发布"),
    agentDataNotFoundWithId("9219", "数据不存在,id=%s", "Data does not exist, id=%s", "数据"),
    agentPluginNotFound("9220", "插件不存在", "Plugin does not exist.", "通用"),
    agentWorkflowNotFoundSimple("9221", "工作流不存在", "Workflow does not exist.", "通用"),
    agentNotFound("9222", "智能体不存在", "Agent does not exist.", "通用"),
    agentTableSchemaQueryFailed("9223", "查询表结构定义失败", "Failed to query table schema.", "表结构"),
    agentTemplateConfigInvalid("9224", "该模版配置异常，暂时不可用", "This template configuration is invalid and temporarily unavailable.", "模版"),
    agentSandboxServerStoppedOrRemoved("9225", "关联的agent服务器已停止或已删除", "The associated agent server has stopped or been removed.", "沙箱/电脑"),
    agentSandboxNotFound("9226", "未找到沙盒服务器", "Sandbox server not found.", "沙箱/电脑"),
    agentPrivateComputerDeleteForbidden("9227", "私有电脑的智能体不允许在此删除", "Agents on a private computer cannot be deleted here.", "智能体"),
    agentKnowledgeIdInvalid("9228", "知识ID错误", "Invalid knowledge ID.", "参数"),
    agentPageIdInvalid("9229", "页面ID错误", "Invalid page ID.", "参数"),
    agentArgBooleanDefaultInvalid("9230", "参数[%s]类型为Boolean，默认值只能为true或false", "Parameter [%s] is Boolean; default must be true or false.", "变量"),
    agentArgIntegerDefaultInvalid("9231", "参数[%s]类型为Integer，默认值只能为整数", "Parameter [%s] is Integer; default must be an integer.", "变量"),
    agentArgNumberDefaultInvalid("9232", "参数[%s]类型为Number，默认值只能为数字", "Parameter [%s] is Number; default must be numeric.", "变量"),
    agentVariableNameDuplicated("9233", "变量名[%s]重复", "Duplicate variable name [%s].", "变量"),
    agentVariableSelectOptionsRequired("9234", "变量[%s]的输入类型为下拉选项，请设置下拉参数配置", "Variable [%s] uses a select input; configure dropdown options.", "变量"),
    agentVariablePluginOffline("9235", "变量[%s]引用的插件不存在或已下线", "Plugin referenced by variable [%s] does not exist or is offline.", "变量"),
    agentVariablePluginDataInvalid("9236", "变量[%s]引用的插件数据结构异常", "Invalid plugin data structure for variable [%s].", "变量"),
    agentVariablePluginOutputEmpty("9237", "变量[%s]引用的插件[%s]的输出参数为空", "For variable [%s], output parameters of referenced plugin [%s] are empty.", "变量"),
    agentVariablePluginOptionsMissing("9238", "变量[%s]引用的插件数据结构不符合规，缺少options", "Plugin data for variable [%s] is invalid: missing options.", "变量"),
    agentVariableWorkflowNotFound("9239", "变量[%s]引用的工作流不存在", "Workflow referenced by variable [%s] does not exist.", "变量"),
    agentVariableWorkflowNoOutput("9240", "变量[%s]引用的工作流没有输出参数", "Workflow referenced by variable [%s] has no output parameters.", "变量"),
    agentVariableWorkflowOptionsMissing("9241", "变量[%s]引用的工作流输出数据结构不符合规，缺少options", "Workflow output data for variable [%s] is invalid: missing options.", "变量"),
    agentVariableOptionsMissing("9242", "变量[%s]缺少选项", "Variable [%s] is missing options.", "变量"),
    agentComponentNotFoundOrRemoved("9243", "组件不存在或已删除", "Component does not exist or was removed.", "组件"),
    agentComponentTypeInvalid("9244", "组件类型错误，请检查是否使用了正确的接口", "Invalid component type; verify you are using the correct API.", "组件"),
    agentNotFoundAlt("9245", "Agent不存在", "Agent does not exist.", "智能体"),
    agentPublishedOffline("9246", "智能体未发布或已下架", "Agent is not published or has been taken offline.", "发布"),
    agentPluginOffline("9247", "插件不存在或已下架", "Plugin does not exist or has been taken offline.", "发布"),
    agentWorkflowOffline("9248", "工作流不存在或已下架", "Workflow does not exist or has been taken offline.", "发布"),
    agentSkillOffline("9249", "技能不存在或已下架", "Skill does not exist or has been taken offline.", "发布"),
    agentSkillDownloadDenied("9250", "无技能下载权限", "No permission to download skills.", "权限"),
    agentUnpublishFailedNotPublished("9251", "下架失败，未发布", "Unpublish failed: not published.", "发布"),
    agentViewDenied("9252", "无查看权限", "No permission to view.", "权限"),
    agentConversationNotFound("9253", "会话不存在", "Conversation does not exist.", "会话"),
    agentConversationPermissionDenied("9254", "无智能体会话权限", "No permission for this agent conversation.", "权限"),
    agentOfflineOrNotFound("9255", "智能体不存在或已下架", "Agent does not exist or has been taken offline.", "会话"),
    agentSelectedNotFound("9256", "选择的智能体不存在", "Selected agent does not exist.", "会话"),
    agentScheduledTaskLimitExceeded("9257", "用户在每个智能体进行中的定时任务不能超过%s个", "In-progress scheduled tasks per agent cannot exceed %s.", "定时任务"),
    agentOperationDenied("9258", "无操作权限", "Operation not permitted.", "权限"),
    agentWebAppNotFound("9259", "网页应用不存在", "Web app does not exist.", "自定义页"),
    agentEmbeddingModelDeleteForbidden("9260", "嵌入模型不允许删除", "Embedding model cannot be deleted.", "模型"),
    agentApplyIdInvalid("9261", "applyId错误", "Invalid applyId.", "参数"),
    agentPublishScopeNotSelected("9262", "未选择发布范围", "Publish scope not selected.", "发布"),
    agentPrivateCannotPublishToSquare("9263", "私有电脑的智能体不允许发布到广场", "Agents on a private computer cannot be published to the square.", "发布"),
    agentSpaceNotFound("9264", "空间[%s]不存在", "Space [%s] does not exist.", "发布"),
    agentSpacePublishDenied("9265", "无空间[%s]发布权限", "No permission to publish to space [%s].", "发布"),
    agentSpacePublishReceivingDisabled("9266", "空间[%s]未开启接收发布功能", "Space [%s] has not enabled receiving publications.", "发布"),
    agentSkillConfigParseFailed("9267", "技能配置解析失败", "Failed to parse skill configuration.", "技能"),
    agentUnpublishFailedAlreadyOffline("9268", "下架失败，未发布或已下架", "Unpublish failed: not published or already offline.", "发布"),
    agentUserSpacePublishDenied("9269", "用户无空间发布权限", "User has no permission to publish to spaces.", "发布"),
    agentUserPublishDenied("9270", "用户无发布权限", "User has no publish permission.", "发布"),
    agentUserNoPersonalSpace("9271", "用户没有个人空间", "User has no personal space.", "发布"),
    agentPluginIdInvalid("9272", "pluginId错误", "Invalid pluginId.", "参数"),
    agentPluginIdError("9273", "插件ID错误", "Invalid plugin ID.", "参数"),
    agentPageIdError("9274", "页面Id错误", "Invalid page ID.", "页面"),
    agentPageAgentIdError("9275", "智能体Id错误", "Invalid agent ID.", "页面"),
    agentPageEnvInvalid("9276", "环境错误", "Invalid environment.", "页面"),
    agentPageDatasourceInvalid("9277", "页面数据源错误", "Invalid page data source.", "页面"),
    agentAppAccessDenied("9279", "无应用访问权限", "No permission to access the app.", "权限"),
    agentPageSpacePermissionDenied("9280", "用户无页面所在空间权限", "User has no permission for the page's space.", "权限"),
    agentAgentPermissionDenied("9281", "用户无智能体权限", "User has no permission for this agent.", "权限"),
    agentPageNotBoundToAgent("9282", "调用的智能体未绑定对应页面", "The invoked agent is not bound to the corresponding page.", "页面"),
    agentPageDatasourceNotFound("9283", "请求的数据源不存在", "Requested data source does not exist.", "页面"),
    agentPluginNotPublished("9284", "插件ID错误或未发布", "Invalid plugin ID or plugin not published.", "页面"),
    agentPluginExecuteDenied("9285", "无插件执行权限", "No permission to execute plugin.", "权限"),
    agentExportFileGenerationFailed("9286", "生成导出文件失败", "Failed to generate export file.", "导入导出"),
    agentPermissionDeniedGeneric("9287", "没有权限", "Permission denied.", "权限"),
    agentRelatedOfflineOrNotFound("9288", "相关智能体不存在或已下架", "Related agent does not exist or is offline.", "API"),
    agentConversationIdInvalid("9289", "错误的conversationId", "Invalid conversationId.", "API"),
    agentTempConversationNotFound("9290", "临时会话不存在", "Temporary conversation does not exist.", "临时会话"),
    agentTempConversationExpired("9291", "临时会话已过期", "Temporary conversation has expired.", "临时会话"),
    agentClientDisabled("9292", "智能体客户端已停用", "Agent client is disabled.", "沙箱"),
    agentComputerServerDisabled("9293", "会话所在智能体电脑服务端已停用", "Agent computer server for this session is disabled.", "沙箱"),
    agentClientOffline("9294", "智能体客户端已离线", "Agent client is offline.", "沙箱"),
    agentSandboxCapacityExceeded("9295", "当前过于火爆，请稍后再试", "Service is busy. Please try again later.", "沙箱"),
    agentNotPublishedOrOfflineAlt("9296", "未发布或已下架", "Not published or offline.", "收藏"),
    agentPublishIdInvalid("9297", "发布ID错误", "Invalid publish ID.", "发布"),
    agentMcpServiceNotFoundOrDenied("9298", "选择的MCP服务不存在或没有权限", "Selected MCP service does not exist or access denied.", "MCP"),
    agentMcpToolNotFoundOrDenied("9299", "选择的工具不存在或没有权限", "Selected tool does not exist or access denied.", "MCP"),
    agentPluginRequiredParamMissing("9300", "请填写必要参数[%s]，便于获取返回参数", "Fill required parameter [%s] to obtain return values.", "插件"),
    agentPluginOfflineReplaceRequired("9303", "插件[%s]未发布或已下线，请更换其他适合的插件", "Plugin [%s] is not published or is offline; choose another plugin.", "插件"),
    agentPluginOfflineSimple("9304", "该插件未发布或已下线", "This plugin is not published or is offline.", "插件"),
    agentPluginSpacePermissionDenied("9305", "当前空间没有插件权限", "No plugin permission in this space.", "插件"),
    agentSessionNotFound("9306", "未找到当前会话", "Current session not found.", "文件"),
    agentResourceAccessDenied("9307", "无权访问当前资源", "No permission to access this resource.", "文件"),
    agentRequiredParamEmpty("9308", "必传参数为空", "Required parameter is empty.", "参数"),
    agentContainerServiceCallFailed("9309", "容器服务调用失败", "Container service call failed.", "容器"),
    agentWorkflowMissingStartNode("9313", "工作流缺少开始节点", "Workflow is missing a start node.", "工作流"),
    agentWorkflowMissingEndNode("9314", "工作流缺少结束节点", "Workflow is missing an end node.", "工作流"),
    agentWorkflowSelfReference("9315", "工作流不能引用自己", "Workflow cannot reference itself.", "工作流"),
    agentWorkflowNotPublished("9316", "工作流未发布", "Workflow is not published.", "工作流"),
    agentWorkflowPluginPermissionDenied("9317", "没有插件权限", "No plugin permission.", "工作流"),
    agentWorkflowCannotDeleteTerminalNodes("9319", "不能删除起始节点和结束节点", "Cannot delete start or end nodes.", "工作流"),
    agentWorkflowCannotDeleteLoopTerminalNodes("9320", "不能删除循环起始节点和结束节点", "Cannot delete loop start or end nodes.", "工作流"),
    agentWorkflowStartNodeNotFound("9321", "未找到起始节点", "Start node not found.", "工作流"),
    agentWorkflowCannotCopyTerminalNodes("9322", "不能复制起始节点和结束节点", "Cannot copy start or end nodes.", "工作流"),
    agentWorkflowSpacePermissionDenied("9323", "当前空间没有工作流[%s]的权限", "No permission for workflow [%s] in this space.", "工作流"),
    agentWorkflowNodeCycleEdge("9367", "节点<%s>与节点<%s>存在循环连线", "Cycle edge between node <%s> and node <%s>.", "工作流"),
    agentSkillUploadFileRequired("9327", "请选择要上传的文件", "Please select a file to upload.", "技能"),
    agentSkillFileFormatInvalid("9329", "文件必须是zip/.skill格式，或者为SKILL.md文件", "File must be .zip/.skill or SKILL.md.", "技能"),
    agentSkillTargetSpaceRequired("9330", "请选择目标空间", "Please select a target space.", "技能"),
    agentSkillZipFormatInvalid("9331", "ZIP 文件格式错误或不兼容，请使用标准的 ZIP 压缩格式重新打包文件。错误详情: %s", "Invalid or incompatible ZIP; repack with standard ZIP. Details: %s", "技能"),
    agentSkillFileFormatError("9332", "文件格式错误，请上传正确的技能文件。错误详情: %s", "Invalid file format; upload a valid skill file. Details: %s", "技能"),
    agentSkillFileSizeExceeded100m("9333", "文件大小不能超过 100M", "File size cannot exceed 100 MB.", "技能"),
    agentSkillReadSkillMdFailed("9334", "读取 SKILL.md 文件失败", "Failed to read SKILL.md.", "技能"),
    agentSkillMdRequired("9335", "技能包中缺少必需的 SKILL.md 文件", "Required SKILL.md is missing from the skill package.", "技能"),
    agentSkillMdNameDescRequired("9336", "SKILL.md 文件中必须包含 name 和 description 信息", "SKILL.md must include name and description.", "技能"),
    agentSkillTemplateReadFailed("9337", "读取技能模板失败: %s", "Failed to read skill template: %s", "技能"),
    agentSkillNotFoundOrDenied("9338", "技能不存在或无权限使用", "Skill does not exist or access denied.", "技能"),
    agentSkillFilePathInvalid("9339", "filePath 无效", "Invalid filePath.", "技能"),
    agentSkillUploadProcessFailed("9340", "处理上传文件失败: %s", "Failed to process uploaded file: %s", "技能"),
    agentSkillMdDeleteForbidden("9343", "SKILL.md 文件不允许删除", "SKILL.md cannot be deleted.", "技能"),
    agentSkillDirRenameFailed("9344", "目录重命名失败，源目录不存在或为空", "Failed to rename directory: source missing or empty.", "技能"),
    agentSkillFileRenameFailed("9345", "文件重命名失败，源文件不存在", "Failed to rename file: source does not exist.", "技能"),
    agentSkillRenameSourceMissing("9346", "缺少文件重命名的源文件名", "Source file name for rename is missing.", "技能"),
    agentSkillUnknownFileOperation("9347", "未知的文件操作类型", "Unknown file operation type.", "技能"),
    agentSkillSingleFileSizeExceeded("9348", "单个文件大小不能超过 100M", "Single file size cannot exceed 100 MB.", "技能"),
    agentSkillExportFailed("9349", "导出技能失败", "Failed to export skill.", "技能"),
    agentDefaultModelDeleteForbidden("9350", "默认模型不允许删除", "Default model cannot be deleted.", "模型"),
    agentModelNotFound("9351", "模型不存在", "Model does not exist.", "模型"),
    agentModelJsonInvalid("9352", "模型返回的JSON格式不正确，请检查提示词", "Invalid JSON from model; check your prompt.", "模型"),
    agentWorkspaceCreateFailed("9353", "创建工作空间失败", "Failed to create workspace.", "工作空间"),
    agentSkillZipPackFailed("9354", "打包技能 zip 失败", "Failed to pack skill zip.", "工作空间"),
    agentSkillFilePushFailed("9355", "推送技能文件失败", "Failed to push skill files.", "工作空间"),
    agentSkillAgentPackFailed("9356", "打包 skill/agent 失败", "Failed to pack skill/agent.", "工作空间"),
    agentCodeExecuteUnavailable("9357", "代码执行接口暂不可用，请稍后再试", "Code execution is temporarily unavailable. Try again later.", "代码执行"),
    agentPluginTypeInvalid("9358", "插件类型错误", "Invalid plugin type.", "插件执行"),
    agentSkillNotFound("9359", "技能不存在", "Skill does not exist.", "技能"),
    agentOpenapiPluginIdInvalid("9360", "pluginId 错误", "Invalid pluginId.", "OpenAPI 英文"),
    agentOpenapiExecutePermissionDenied("9361", "无执行权限", "Execute permission denied.", "OpenAPI 英文"),
    agentOpenapiModelIdInvalid("9362", "model id 错误", "Invalid model id.", "OpenAPI 英文"),
    agentOpenapiConversationIdInvalid("9363", "conversationId 错误", "Invalid conversationId.", "OpenAPI 英文"),
    agentOpenapiPluginNotFound("9364", "Plugin不存在", "Plugin does not exist.", "英文资源名"),
    agentOpenapiSkillNotFound("9366", "Skill不存在", "Skill does not exist.", "英文资源名"),

    /** 沙箱 / 电脑连接与状态 */
    agentComputerConnectFailed("9371", "智能体电脑连接失败", "Failed to connect to agent computer.", "沙箱"),
    agentStatusQueryResponseInvalid("9372", "状态查询返回数据结构异常", "Invalid status query response structure.", "沙箱"),
    agentComputerStartupFailed("9373", "智能体电脑启动失败，请重试", "Failed to start agent computer. Please retry.", "沙箱"),

    /** 助手 / 表查询（与「表结构定义」文案区分） */
    agentAssistantTableSchemaQueryFailed("9375", "查询表结构失败", "Failed to query table schema.", "助手"),

    /** 工作流节点执行 */
    agentWorkflowMcpReferenceRemoved("9377", "节点引用的MCP服务已被删除", "MCP service referenced by the node has been deleted.", "工作流"),
    agentWorkflowLoopNotFullyConnected("9378", "循环节点未完整连接", "Loop nodes are not fully connected.", "工作流"),
    agentWorkflowLoopMaxCountInvalid("9379", "循环节点最大循环次数不能小于等于0", "Loop max iterations must be greater than 0.", "工作流"),
    agentWorkflowConditionBranchesEmpty("9380", "条件分支列表不能为空", "Condition branch list cannot be empty.", "工作流");


    /**
     * 错误码
     */
    private final String code;
    /**
     * 中文提示模板（与 {@link String#format} 占位一致）
     */
    private final String messageZh;
    /**
     * 英文提示模板
     */
    private final String messageEn;
    /**
     * 分类备注,方便看异常定义,不参与错误提示
     */
    private final String remark;


    BizExceptionCodeEnum(String code, String messageZh, String messageEn, String remark) {
        this.code = code;
        this.messageZh = messageZh;
        this.messageEn = messageEn;
        this.remark = remark;
    }


}
